---
# tasks file for mariadb
- name: Check variables
  assert:
    that:
      - mariadb_version is defined
      - mariadb_root_password is defined
      - galera_cluster_bind_interface is defined
      - galera_cluster_name is defined
      - groups[galera_cluster_nodes_group] is defined
      - mariadb_mysql_settings is defined

- include: install_mariadb.yml
  tags:
    - install

- include: setup_galera.yml
  tags:
    - galera
