---
- name: Galera | checking if galera cluster setup
  stat:
    path: "/etc/galera_cluster_configured"
  register: "galera_cluster_configured"

- name: Firewall | Check if ufw is installed
  command: "which ufw"
  become: true
  ignore_errors: true
  check_mode: no
  changed_when: false
  register: check_ufw

- name: Firewall | Ensure galera ports are accessable
  ufw:
    rule: allow
    direction: in
    comment: MariaDB Galera Cluster
    proto: "{{ item.proto }}"
    to_port: "{{ item.to_port }}"
  with_items:
    - { to_port: 4444, proto: tcp }
    - { to_port: 4567, proto: tcp }
    - { to_port: 4567, proto: udp }
    - { to_port: 4568, proto: tcp }
  when: check_ufw.rc == 0

- name: Galera | configuring db server and galera
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  become: true
  register: "_mariadb_galera_cluster_reconfigured_1"
  with_items:
    - 'etc/mysql/conf.d/galera.cnf'

- name: Galera | stopping mysql
  service:
    name: "mysql"
    state: "stopped"
  become: true
  when: not galera_cluster_configured.stat.exists

- name: Galera | killing lingering mysql processes
  command: "pkill mysqld"
  become: true
  ignore_errors: true
  when: not galera_cluster_configured.stat.exists

- name: Galera | configuring temp galera config
  template:
    src: "etc/mysql/conf.d/temp.galera.cnf.j2"
    dest: "/etc/mysql/conf.d/galera.cnf"
  become: true
  when:
    - not galera_cluster_configured.stat.exists
    - inventory_hostname == galera_mysql_master_node

- name: Galera | bootstrapping galera cluster
  service:
    name: "mysql"
    state: "restarted"
  become: true
  when:
    - not galera_cluster_configured.stat.exists
    - inventory_hostname == galera_mysql_master_node

- name: Galera | bootstrapping galera cluster
  command: "/usr/bin/galera_new_cluster"
  become: true
  when:
    - not galera_cluster_configured.stat.exists
    - inventory_hostname == galera_mysql_master_node

- name: Galera | joining galera cluster
  service:
    name: "mysql"
    state: "restarted"
  become: true
  when:
    - not galera_cluster_configured.stat.exists
    - inventory_hostname != galera_mysql_master_node

- name: Galera | configuring galera on mysql_master
  template:
    src: "etc/mysql/conf.d/galera.cnf.j2"
    dest: "/etc/mysql/conf.d/galera.cnf"
  become: true
  register: "_mariadb_galera_cluster_reconfigured_2"
  when:
    - not galera_cluster_configured.stat.exists
    - inventory_hostname == galera_mysql_master_node

- name: Galera | restarting galera on mysql_master
  service:
    name: "mysql"
    state: "restarted"
  become: true
  when:
    - not galera_cluster_configured.stat.exists
    - inventory_hostname == galera_mysql_master_node

- name: Galera | marking galera cluster as configured
  file:
    path: "/etc/galera_cluster_configured"
    state: "touch"
  become: true
  when: not galera_cluster_configured.stat.exists

# Only restart if cluster has already been configured
- name: Galera | Restarting MySQL (Master)
  service:
    name: "mysql"
    state: "restarted"
  become: true
  register: "_mariadb_galera_cluster_master_restarted"
  when: >
        (galera_cluster_configured.stat.exists and
        inventory_hostname == galera_mysql_master_node) and
        (_mariadb_galera_cluster_reconfigured_1.changed or
        _mariadb_galera_cluster_reconfigured_2.changed)
  tags:
    - skip_ansible_lint

- name: Galera | Waiting For MySQL (Master)
  wait_for:
    port: "{{ mariadb_mysql_settings['port'] }}"
    host: "{{ galera_cluster_bind_address }}"
  when:
    - inventory_hostname == galera_mysql_master_node
    - _mariadb_galera_cluster_master_restarted.changed

# Only restart if cluster has already been configured
- name: Galera | Restarting MySQL (Non-Master)
  service:
    name: "mysql"
    state: "restarted"
  become: true
  register: "_mariadb_galera_cluster_non_master_restarted"
  when: >
        (galera_cluster_configured.stat.exists and
        inventory_hostname != galera_mysql_master_node) and
        (_mariadb_galera_cluster_reconfigured_1.changed or
        _mariadb_galera_cluster_reconfigured_2.changed)
  tags:
    - skip_ansible_lint

- name: Galera | Waiting For MySQL (Non-Master)
  wait_for:
    port: "{{ mariadb_mysql_settings['port'] }}"
    host: "{{ galera_cluster_bind_address }}"
  when:
    - inventory_hostname != galera_mysql_master_node
    - _mariadb_galera_cluster_non_master_restarted.changed
