apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: celery
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: celery
    spec:
      containers:
      - args:
        - celery
        - -A
        - tasks
        - worker
        - --loglevel=info
        - --logfile=celery.log
        env:
        - name: CELERY_BACKEND
          value: redis://redis:6379/0
        - name: CELERY_BROKER
          value: redis://redis:6379/0
        image: jorehn/vlanscanner:0.1
        imagePullPolicy: ""
        name: celery
        resources: {}
        tty: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
