version: '3.1'

services:
   restservice:
     image: jorehn/vlanscanner:0.1
     command: gunicorn -c ../gunicorn_conf.py vlanscanner:API
     ports:
       - "8000:8000"
     environment:
       - CELERY_BROKER=redis://redis:6379/0
       - CELERY_BACKEND=redis://redis:6379/0
     depends_on:
       - redis
     tty: true
   celery:
     image: jorehn/vlanscanner:0.1
     command: celery -A tasks worker --loglevel=info --logfile=celery.log
     environment:
       - CELERY_BROKER=redis://redis:6379/0
       - CELERY_BACKEND=redis://redis:6379/0
     depends_on:
       - redis
       - restservice
     tty: true
   monitor:
     image: jorehn/vlanscanner:0.1
     command: flower -A tasks --port=5555 --broker=redis://redis:6379/0
     ports:
       - "5555:5555"
     depends_on:
       - restservice
       - redis
   redis:
     image: redis:latest
