apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: monitor
  name: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monitor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: monitor
    spec:
      containers:
      - args:
        - flower
        - -A
        - tasks
        - --port=5555
        - --broker=redis://redis:6379/0
        image: jorehn/vlanscanner:0.1
        imagePullPolicy: ""
        name: monitor
        ports:
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
