---
# tasks file for common
- name: APT - Install some default packages
  apt:
    update_cache: yes
    name:
      - vim
      - rsync
      - bash-completion
      - apt-transport-https
      - software-properties-common

- name: APT - Add MariaDB Repo Key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present

- name: APT - Add MariaDB Repo
  apt_repository:
    repo: "deb [arch=amd64] http://ams2.mirrors.digitalocean.com/mariadb/repo/{{ mariadb_version }}/ubuntu bionic main"
    state: present
    filename: mariadb
    update_cache: yes

- name: APT - Run a dist-upgrade
  apt:
    update_cache: yes
    upgrade: dist
