---
# tasks file for common
- name: APT - Install some default packages
  apt:
    update_cache: yes
    name:
      - vim
      - rsync
      - bash-completion
      - apt-transport-https
      - software-properties-common
