all:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            95.217.165.199:
              ansible_user: root
              extra_server_args: ''
              k3s_version: v0.8.1
              master_ip: '{{ hostvars[groups[''master''][0]][''ansible_host''] | default(groups[''master''][0])
                }}'
              systemd_dir: /etc/systemd/system
        node:
          hosts:
            95.217.163.219:
              ansible_user: root
              extra_server_args: ''
              k3s_version: v0.8.1
              master_ip: '{{ hostvars[groups[''master''][0]][''ansible_host''] | default(groups[''master''][0])
                }}'
              systemd_dir: /etc/systemd/system
            95.217.165.111:
              ansible_user: root
              extra_server_args: ''
              k3s_version: v0.8.1
              master_ip: '{{ hostvars[groups[''master''][0]][''ansible_host''] | default(groups[''master''][0])
                }}'
              systemd_dir: /etc/systemd/system
            95.217.167.211:
              ansible_user: root
              extra_server_args: ''
              k3s_version: v0.8.1
              master_ip: '{{ hostvars[groups[''master''][0]][''ansible_host''] | default(groups[''master''][0])
                }}'
              systemd_dir: /etc/systemd/system
    ungrouped: {}
