---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false

  tasks:
    - name: Destroy Instance
      include_tasks: tasks/destroy_instance.yml
      loop: "{{ molecule_yml.platforms }}"


    - name: Populate instance config
      set_fact:
        instance_conf: {}


    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: instance.changed | bool
